development:
  adapter: postgresql
  encoding: unicode
  database: blogapp_development
  pool: 5
  host: localhost
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: blogapp_test
  pool: 5
  username: postgres

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 